services:
  zookeeper:
    image: 'bitnami/zookeeper:latest' 
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_HEAP_SIZE=256m
  kafka:
    image: 'bitnami/kafka:3.6.2'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 # Connects to the zookeeper service
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
    depends_on:
      - zookeeper
  producer:
    build: .
    command: python3 kafka_producer.py
    depends_on:
      - kafka
  consumer:
    build: .
    command: python3 backtest.py
    depends_on:
      - kafka